CREATE TABLE IF NOT EXISTS ivr_id ( ivr_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, descname VARCHAR(50));
CREATE TABLE IF NOT EXISTS ivr_dests ( ivr_id INT NOT NULL PRIMARY KEY, selection VARCHAR(10), dest_type VARCHAR(50), dest_id VARCHAR(50));
