#!/usr/bin/env php
<?php
namespace FreePBX\Install;

set_time_limit(0);

require_once('amp_conf/htdocs/admin/libraries/Composer/vendor/autoload.php');
require_once('installlib/installhelpcommand.class.php');
require_once('installlib/installapplication.class.php');
require_once('installlib/installcommand.class.php');

use Symfony\Component\Console\Application;

$xml = simplexml_load_file("module.xml");

$app = new FreePBXInstallApplication("FreePBX Installation Utility", (string)$xml->version);
$app->run();
