<?php

/**
 * @file
 * Functions common to display
 */

/**
  * display constructor 
  */
class Display {

  /**
   * display constructor 
   */
  function Display() {
  }

  /**
   * display text header
   *
   * @param $text
   *   Header text to display
   */
  function DisplayHeaderText($text) {

    $ret = "<h2>" . $text . "</h2>
            <br>";

    return $ret;
  }

  /**
   * Displays header line 
   */
  function DisplayLine() {

    $ret = "
      <br>
      <div id='line'>
        <div class='spacer'></div>
        <div class='spacer'></div>
      </div>
      <br>";

    return $ret;
  }
}  


class DisplaySearch extends Display {

  /**
   * Constructor
   */
  function DisplaySearch() {
  }

  /**
   * Displays search controls
   *
   * @param $align
   *   where to align the control
   * @param $q
   *   search query
   * @param $focus
   *   whether to focus control on this block
   */
  function DisplaySearchBlock($align,$q,$focus) {

    if ($align=='center') {
      $alignText = "id='centerbar'";
    }

    $ret .= "<div " . $alignText . ">
               <form action='" . $_SERVER['PHP_SELF'] . "' method='GET' name='search'>
                 <input type=text name=q size=40 value='" . $q . "' maxlength=256>
                 <input type=hidden name=start value=0>			
                 <input type=submit name=btnS value='Search'>
               </form>
             </div>";

    if ($focus=="true") {	// search block loaded twice usually so only allow javascript to be loaded on the top block
      $ret .= "<script type='text/javascript'> 
                 <!-- 
                 if (document.search) { 
                   document.search.query.focus(); 
                 } 
                 // -->                
               </script>";
    }

    return $ret;
  }

  /**
   * Displays info bar
   *
   * @param $q
   *   search query
   * @param $start
   *   start number of current page
   * @param $span
   *   number of items on current page
   * @param $total
   *   total number of records found by current search
   */
  function DisplayInfoBarBlock($q,$start,$span,$total) {

    if ($total<$span) { 
      $span = $total; 
    }
    $startCount = ($total>0)?$start+1:$start;
    $spanCount = ($start+$span>$total)?$total:$start+$span;

    if ($q != NULL) {
      $searchedForText = "<small><small>Searched for <u>" . $q . "</u></small></small>";
    }

    if ($span<$total) {
      $recordCountText = "<small><small>Results " . $startCount . " - " . $spanCount . " of " . $total . "</small></small>";
    } else {
      $recordCountText = "<small><small>Results " . $total . "<small></small>";
    }

    $ret .= "<div id='navbar'>
               <span class='left'>
               " . $searchedForText ."
               </span>
               <span class='right'>
               " . $recordCountText ."
               </span>
             </div>";

    return $ret;
  }

  /**
   * Displays info bar
   *
   * @param $q
   *   search query
   * @param $start
   *   start number of current page
   * @param $span
   *   number of items on current page
   * @param $total
   *   total number of records found by current search
   */
  function DisplayNavigationBlock($q,$start,$span,$total) {

    // add navigation to bottom of page
    $totalPages = ceil($total/$span);
    $startPage = floor($start/$span);

    // encode search string
    $q = urlencode($q);

    // if more than ten pages start at this page minus ten otherwise start at zero
    $begin = ($startPage>10)?($startPage-10):0;
    // if more than ten pages then stop at this page plus ten otherwise stop at last page
    $end = ($startPage>8)?($startPage+10):10;

    $url = $_SERVER['PHP_SELF'] . "?q=" . $q;

    if ($startPage!=0) {
      $startPageText = "<a href='" . $url . "&start=0'><small>First</a>&nbsp;</small>
			<a href=" . $url . "&start=" . ($start-$span) . "><small><</a>&nbsp;</small>";
    }

    for($nextPage=$begin;($nextPage<$totalPages)&&($nextPage<$end);$nextPage++) {
      if ($nextPage == $startPage) {
          $middlePageText .= "<a href='" . $url . "&start=0'><small>" . ($nextPage+1) . "</a>&nbsp;</small>";
      } else {
          $middlePageText .= "<a href='" . $url . "&start=" . ($nextPage*$span) . "'><small>" . ($nextPage+1) . "</a>&nbsp;</small>";
      }
    }
    if ( ($startPage != $totalPages-1)  && ($total != 0) ) {
          $endPageText = "<a href='" . $url . "&start=" . ($totalPages-1)*$span . "'><small>></a>&nbsp;</small>
                          <a href='" . $url . "&start=" . ($start+$span) . "'><small>Last</a>&nbsp;</small>";
    }

    $ret .= "<div id='centerbar'>
              " . $startPageText . "
              " . $middlePageText . "
              " . $endPageText . "
             </div>";

    return $ret;
  }
}  


?>