<?php
global $amp_conf;
include_once ($amp_conf['AMPWEBROOT'].'/admin/libraries/freepbx_conf.class.php');
$freepbx_conf =& freepbx_conf::create();

if (!$freepbx_conf->conf_setting_exists('REMOTEUNLOCK')) {
        $set['category'] = 'System Setup';
        $set['level'] = 2;
        $set['value'] = false;
        $set['defaultval'] = false;
        $set['options'] = '';
        $set['name'] = 'Enable Remote Unlocking';
        $set['description'] = 'Enabling this option will allow a remote user to automatically authenticate as an admin via use of a one-time key generated by "amportal a genunlockkey"';
        $set['emptyok'] = 0;
        $set['readonly'] = 0;
        $set['hidden'] = 0;
        $set['type'] = CONF_TYPE_BOOL;
        $freepbx_conf->define_conf_setting('REMOTEUNLOCK',$set);
}
