#!/bin/bash

YUMCMD="makecache fast"
RESULTS=/dev/shm/yum-makecache

# Make sure we're not already running
if [ -e /var/run/yum.pid ]; then
	PID=$(cat /var/run/yum.pid)
	if [ -e /proc/$PID ]; then
		echo "## ERROR ## - $(date) - '$YUMCMD' - Yum already running" | tee /dev/shm/yum.error
		exit
	fi
fi

rm -f $RESULTS
echo START=$(/bin/date '+%s') > $RESULTS
chmod 644 $RESULTS

OUTPUT=$(/usr/bin/yum --setopt=exit_on_lock=true $YUMCMD 2>&1)
EXITCODE=$?
ENCODED=$(echo "$OUTPUT" | base64 -w0)

if [ "$EXITCODE" -ne "0" ]; then
	echo "## ERROR ## - $(date) - '$YUMCMD' - Exitcode $EXITCODE - Ouput $ENCODED" | tee /dev/shm/yum.error
	echo STATUS=error >> $RESULTS
else
	echo STATUS=complete >> $RESULTS
fi
echo EXITCODE=$EXITCODE >> $RESULTS
echo OUTPUT=$ENCODED >> $RESULTS
echo END=$(/bin/date '+%s') >> $RESULTS

