#!/bin/bash -x

OUTDIR=/dev/shm/yumwrapper
mkdir -p $OUTDIR
config="logfile $OUTDIR/output.log
logfile flush 1
log on
logtstamp on
logtstamp after 1
logtstamp string \"[ %t: %Y-%m-%d %c:%s ]\012\"
"

# The script automatically cleans up BEFORE itself,
# as there's no need for any of it to hang around.
script='#!/bin/bash
# Function to wait for a lock to be available
# Waits for $2 seconds, default is 30.
function lock() {
	local defaultwait=30
	local lockfile='${OUTDIR}'/${1}.lock
	local waittime=${2:-$defaultwait}
	eval "exec 10>$lockfile"
	while [[ $waittime > 0 ]]; do
		# Try to get a lock on our lockfile
		flock -w 1 10 && return 0
		waittime=$(( $waittime - 1 ))
		sleep 1
	done
	return 1
}
TMPDIR=$(dirname $0)
cd /tmp
rm -rf $TMPDIR
lock yum 300  # Wait for up to 5 mins.
echo START: yum-clean-metadata
#yum clean metadata
echo STOP: yum-clean-metadata $?
echo START: yum-check-updates
yum -q check-updates
echo STOP: yum-check-updates $?
'

# Create our tmpdir, and put our config and script in there.
T=$(mktemp -d)

echo "$config" > $T/command.conf
echo "$script" > $T/script.sh
chmod 755 $T/script.sh
screen -c $T/command.conf -dmSL 'freepbx' $T/script.sh

